package org.codegen.Handler;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.File;

public class directoryHandler {
    private static final Logger log = LoggerFactory.getLogger(directoryHandler.class);
   public static String outerDirectoryPath="C:\\Users\\di.garg1\\Desktop\\Autogenerated";
   public static String outerScriptDirectoryPath="C:\\Users\\di.garg1\\Desktop\\MySql_Sripts\\DummyScript.sql";
    public static void directoryCreation(String directoryPath)
    {
        File file = new File(directoryPath);
        if(file.isDirectory())
            log.info("Directory already exists");
        else {
            file.mkdirs();
            log.info("Directory created--->"+directoryPath);
        }
    }
    public static String getScriptName()
    {
        File scriptName= new File(outerScriptDirectoryPath);
        log.info("Fetching Script name");
        return scriptName.getName().replace(".sql","");
    }

    public static String generatedDirectoryPath()
    {
        log.info("Generated outer Directory Path");
        return outerDirectoryPath+"\\src\\main\\java\\com\\gemini\\"+getScriptName();
    }

}
