package org.gemini.codegen.Handler;
import org.apache.commons.io.FileUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.io.File;
import java.io.FilenameFilter;
import java.util.List;


public class DirectoryHandler {

    private static final Logger LOG = LoggerFactory.getLogger(DirectoryHandler.class);
//   public static String outerDirectoryPath= System.getProperty("directoryPath").replaceAll("[/\\\\]+","/");
//   public static String outerScriptDirectoryPath=System.getProperty("scriptPath").replaceAll("[/\\\\]+","/");
    public static String outerDirectoryPath=("C:\\Users\\di.garg1\\Desktop\\Autogenerated").replaceAll("[/\\\\]+","/");
    public static String outerScriptDirectoryPath=("C:\\Users\\di.garg1\\Desktop\\MySql_Sripts\\DummyScript.sql").replaceAll("[/\\\\]+","/");
    public static String url=System.getProperty("url");
    public static String driverClassName=System.getProperty("driverClassName");
    public static String username=System.getProperty("username");
    public static String password=System.getProperty("password");


    /**
     * createDirectory() method is used to create new directory.
     *
     * @param directoryPath
     */
    public static void createDirectory(String directoryPath)
    {
        File file = new File(directoryPath);
        if(file.isDirectory())
            LOG.info("Directory already exists");
        else {
            file.mkdirs();
            LOG.info("Directory created---> {}",directoryPath);
        }
    }

    /**
     * getScriptName() method is used to get script name.
     *
     * @return scriptName
     */
    public static String getScriptName()
    {
        File scriptName= new File(outerScriptDirectoryPath);
        return scriptName.getName().replace(".sql","");
    }

    /**
     * getSchemaName() method is used to get Schema name in script.
     *
     * @return schemaName
     */
    public static String getSchemaName() {
        File schemaName= new File(DirectoryHandler.generateDirectoryPath()+"/entity");
        String[] directories = schemaName.list(new FilenameFilter() {
            @Override
            public boolean accept(File current, String name) {
                return new File(current, name).isDirectory();
            }
        });
        if(directories[0]==null)
            throw new NullPointerException("Script does not contain Schema Name.");
        return directories[0];
    }

    /**
     * generateDirectoryPath() method is used to rename a directory.
     *
     * @return generateDirectoryPath
     */
    public static String generateDirectoryPath()
    {
        StringBuilder path=new StringBuilder();
        path.append(outerDirectoryPath);
        path.append("/");
        path.append(getScriptName());
        path.append("SpringBootApp/src/main/java/com/gemini/");
        path.append(getScriptName());
        return path.toString();
    }

    /**
     * renameDirectory() method is used to rename a directory.
     *
     * @param filePath
     */
    public static void renameDirectory(File filePath, File renameFilePath){
        if(filePath.renameTo(renameFilePath)) {
            LOG.info("File moved successfully");
        }
        else {
            LOG.info("Failed to move the file");
        }
    }


    /**
     * deleteDirectory() method is used to delete a directory.
     *
     * @param filePath
     */
    public static void deleteDirectory(String filePath)  {
        File file =new File(filePath);
        try {
            if (file.isDirectory()) {
                FileUtils.deleteDirectory(file);
                LOG.info("Directory deleted successfully : {}", file);
            } else {
                LOG.info("Directory does not exist");
            }
        }
        catch (Exception e){
            LOG.info(e.getMessage(),e.getCause());
        }
    }

    /**
     * deleteFiles() method is used to delete files of a directory.
     *
     * @param filePath
     * @param classNames
     */
    public static void deleteFiles(List<String> classNames, String filePath){
        for (String className:classNames) {
            File file = new File(filePath+"/"+className+".class");
            if (file.exists()) {
                file.delete();
                LOG.info("{}.class deleted successfully",className);
            } else {
                LOG.info("{}.class does not exist",className);
            }

        }
    }

}
