/*
 * This file is generated by jOOQ.
 */
package entity.demo;


import entity.demo.tables.Language;


/**
 * Convenience access to all tables in DEMO.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>DEMO.LANGUAGE</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
