package org.codegen;

import org.codegen.ApiCodeGen.loader.ClassLoaderTest;
import org.codegen.Handler.directoryHandler;
import org.codegen.Handler.templateHandler;
import org.codegen.JOOQ.PojosGen.EntityClassGen;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static java.nio.file.Paths.get;

public class Main extends ClassLoader {
    private static final Logger log = LoggerFactory.getLogger(Main.class);


    public static void main(String[] args) throws IOException {

        directoryHandler.directoryCreation(directoryHandler.generatedDirectoryPath());
        log.info("<------ CodeGen FrameWork Started ------>");
        try {
            EntityClassGen.EntityGenerator(directoryHandler.outerScriptDirectoryPath, "com.gemini."+directoryHandler.getScriptName()+".entity",directoryHandler.generatedDirectoryPath());
        } catch (Exception e) {
            log.error("Exception in generating POJO classes {}", e.getMessage());
        }

        File file = new File("C:\\Users\\di.garg1\\Desktop\\Autogenerated\\src\\main\\java\\com\\gemini\\DummyScript\\com\\gemini\\DummyScript\\entity");
        // renaming the file and moving it to a new location
        if(file.renameTo
                (new File("C:\\Users\\di.garg1\\Desktop\\Autogenerated\\src\\main\\java\\com\\gemini\\DummyScript\\entity")))
        {
            // if file copied successfully then delete the original file
            file.delete();
            System.out.println("File moved successfully");
        }
        else
        {
            System.out.println("Failed to move the file");
        }

//        Path temp = Files.move
//                (Paths.get("C:\\Users\\di.garg1\\Desktop\\Autogenerated\\src\\main\\java\\com\\gemini\\DummyScript\\com\\gemini\\DummyScript\\entity"),
//                        Path.of("C:\\Users\\di.garg1\\Desktop\\Autogenerated\\src\\main\\java\\com\\gemini\\DummyScript\\entity"));
//
//        if(temp != null)
//        {
//                                        file.delete();
//            System.out.println("File renamed and moved successfully");
//        }
//        else
//        {
//            System.out.println("Failed to move the file");
//        }

        List<String> classnames= ClassLoaderTest.loadClass(ClassLoaderTest.readClass());
        System.out.println(classnames);
        ClassLoaderTest.convertIntoAPIJson();
        templateHandler.generateSpringBootProject(classnames);

//        Handlebar.SwaggerYaml();
//        try {
//           GenerateSpringBootProject.generateProject("src/main/resources/SwaggerYaml.yml", "spring", "io.codejournal.maven.swagger2java.api", "io.codejournal.maven.swagger2java.model", "io.codejournal.maven.swagger2java.handler", "src/main/java/org/Autogenerated");
//        } catch (Exception e) {
//            log.error("Exception in generating SpringBoot Project {}", e.getMessage());
//        }




    }

}
