package org.codegen;

import org.codegen.ApiCodeGen.loader.Classloader;
import org.codegen.ApiCodeGen.templateHandler.Handlebar;
import org.codegen.JOOQ.PojosGen.EntityClassGen;
import org.codegen.SwaggerCodeGen.GenerateSpringBootProject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;

public class Main extends ClassLoader {
    private static final Logger log = LoggerFactory.getLogger(Main.class);
    static GenerateSpringBootProject generateSpringBootProject = new GenerateSpringBootProject();


    public static void main(String[] args) {

        log.info("<------ CodeGen FrameWork Started ------>");
        try {
            System.out.println("Start Time" + System.currentTimeMillis());
            EntityClassGen.EntityGenerator("src/main/resources/Script.sql", "C:\\Users\\di.garg1\\Desktop\\POJOS\\entity", "C:\\Users\\di.garg1\\Desktop\\POJOS");
            System.out.println("End Time" + System.currentTimeMillis());
        } catch (Exception e) {
            log.error("Exception in generating POJO classes {}", e.getMessage());
        }
        File[] files = new File("C:\\Users\\di.garg1\\Desktop\\POJOS\\C_3a_5cUsers_5cdi\\garg1_5cDesktop_5cPOJOS_5centity\\tables\\pojos").listFiles();
        System.out.println(files.length);

//        Classloader.loadClass(Classloader.readClass());
//        Classloader.convertIntoAPIJson();
//        Handlebar.SwaggerYaml();
//        try {
//            generateSpringBootProject.generateProject("src/main/resources/SwaggerYaml.yml", "spring", "io.codejournal.maven.swagger2java.api", "io.codejournal.maven.swagger2java.model", "io.codejournal.maven.swagger2java.handler", "src/main/java/org/Autogenerated");
//        } catch (Exception e) {
//            log.error("Exception in generating SpringBoot Project {}", e.getMessage());
//        }


    }

}
