package org.codegen;

import org.codegen.ApiCodeGen.loader.ClassLoaderTest;
import org.codegen.ApiCodeGen.loader.Classloader;
import org.codegen.ApiCodeGen.templateHandler.Handlebar;
import org.codegen.JOOQ.PojosGen.EntityClassGen;
import org.codegen.SwaggerCodeGen.GenerateSpringBootProject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;

public class Main extends ClassLoader {
    private static final Logger log = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {

        log.info("<------ CodeGen FrameWork Started ------>");
        try {
            EntityClassGen.EntityGenerator("src/main/resources/DummyScript.sql", "entity", "C:\\Users\\di.garg1\\Desktop\\POJOS");
        } catch (Exception e) {
            log.error("Exception in generating POJO classes {}", e.getMessage());
        }
//        Classloader.loadClass(Classloader.readClass());
        ClassLoaderTest.loadClass(ClassLoaderTest.readClass());
        ClassLoaderTest.convertIntoAPIJson();
        Handlebar.SwaggerYaml();
        try {
           GenerateSpringBootProject.generateProject("src/main/resources/SwaggerYaml.yml", "spring", "io.codejournal.maven.swagger2java.api", "io.codejournal.maven.swagger2java.model", "io.codejournal.maven.swagger2java.handler", "src/main/java/org/Autogenerated");
        } catch (Exception e) {
            log.error("Exception in generating SpringBoot Project {}", e.getMessage());
        }

//        ClassLoaderTest.loadClass();


    }

}
